# Generated by Django 4.0.1 on 2022-02-01 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_usuario',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False),
        ),
    ]
